version: '3.8'

services:
    eltako:
      build: 
        dockerfile: ./docker/Dockerfile
        context: ..
        args:
          progress: plain
      ports:
        - "8081:8080"
      devices:
        - "/dev/ttyUSB1:/dev/ttyUSB1"
      networks:
        - mosquitto
      environment:
        ELTAKO_MQTT_URL: mqtt://mosquitto:1883
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        networks:
            - mosquitto
networks:
    mosquitto:
        name: mosquitto
        driver: bridge